<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addalcheckanalysis extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('alcheck_analysis', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 3,
              'fixed' => false,
              'unsigned' => true,
              'primary' => true,
              'autoincrement' => true,
             ),
             'sample_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => true,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
             ),
             'alcheck_batch_id' => 
             array(
              'type' => 'integer',
              'length' => 2,
              'fixed' => false,
              'unsigned' => true,
              'primary' => false,
              'default' => '0',
              'notnull' => true,
              'autoincrement' => false,
             ),
             'number_within_batch' => 
             array(
              'type' => 'integer',
              'length' => 1,
              'fixed' => false,
              'unsigned' => true,
              'primary' => false,
              'default' => '0',
              'notnull' => true,
              'autoincrement' => false,
             ),
             'sample_name' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => NULL,
             ),
             'bkr_number' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => NULL,
             ),
             'wt_bkr_tare' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => true,
              'autoincrement' => false,
             ),
             'flag_bkr_tare_avg' => 
             array(
              'type' => 'integer',
              'length' => 1,
              'fixed' => false,
              'unsigned' => true,
              'primary' => false,
              'default' => '0',
              'notnull' => true,
              'autoincrement' => false,
             ),
             'wt_bkr_sample' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => true,
              'autoincrement' => false,
             ),
             'wt_bkr_soln' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => false,
              'autoincrement' => false,
             ),
             'icp_al' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => false,
              'autoincrement' => false,
             ),
             'icp_ba' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => false,
              'autoincrement' => false,
             ),
             'icp_be' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => false,
              'autoincrement' => false,
             ),
             'icp_ca' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => false,
              'autoincrement' => false,
             ),
             'icp_fe' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => false,
              'autoincrement' => false,
             ),
             'icp_k' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => false,
              'autoincrement' => false,
             ),
             'icp_mg' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => false,
              'autoincrement' => false,
             ),
             'icp_mn' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => false,
              'autoincrement' => false,
             ),
             'icp_na' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => false,
              'autoincrement' => false,
             ),
             'icp_ti' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => false,
              'autoincrement' => false,
             ),
             'addl_dil_factor' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '1.00',
              'notnull' => true,
              'autoincrement' => false,
             ),
             'notes' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('alcheck_analysis');
    }
}