<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addicprun extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('icp_run', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => true,
              'primary' => true,
              'autoincrement' => true,
             ),
             'split_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => true,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
             ),
             'run_num' => 
             array(
              'type' => 'integer',
              'length' => 1,
              'fixed' => false,
              'unsigned' => true,
              'primary' => false,
              'default' => '1',
              'notnull' => true,
              'autoincrement' => false,
             ),
             'al_result' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => true,
              'autoincrement' => false,
             ),
             'be_result' => 
             array(
              'type' => 'float',
              'length' => 18,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0.00',
              'notnull' => true,
              'autoincrement' => false,
             ),
             'use_al' => 
             array(
              'type' => 'string',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => 'y',
              'notnull' => true,
              'autoincrement' => false,
             ),
             'use_be' => 
             array(
              'type' => 'string',
              'length' => 1,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => 'y',
              'notnull' => true,
              'autoincrement' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('icp_run');
    }
}