<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addprojectsample extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('project_sample', array(
             'project_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => true,
              'primary' => true,
              'autoincrement' => false,
             ),
             'sample_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => true,
              'primary' => true,
              'autoincrement' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'project_id',
              1 => 'sample_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('project_sample');
    }
}