<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsilcl36batch extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sil_cl36_batch', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => true,
              'primary' => true,
              'autoincrement' => true,
             ),
             'owner' => 
             array(
              'type' => 'string',
              'length' => 60,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
             ),
             'cl_carrier_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sil_cl36_batch');
    }
}