<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version25 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('al_carrier', 'r26to27', 'float', '', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('al_carrier', 'r26to27_error', 'float', '', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('be_carrier', 'r10to9', 'float', '', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('be_carrier', 'r10to9_error', 'float', '', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('al_carrier', 'r26to27');
        $this->removeColumn('al_carrier', 'r26to27_error');
        $this->removeColumn('be_carrier', 'r10to9');
        $this->removeColumn('be_carrier', 'r10to9_error');
    }
}