<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('al_ams', 'r_to_rstd', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('al_ams', 'interror', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('al_ams', 'exterror', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('al_ams', 'truefrac', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('al_ams_std', 'r26to27', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('al_ams_std', 'error', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('al_carrier', 'al_conc', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('al_carrier', 'del_al_conc', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('al_carrier', 'r26to27', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('al_carrier', 'r26to27_error', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'wt_bkr_tare', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'wt_bkr_sample', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'wt_bkr_soln', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_al', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_ba', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_be', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_ca', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_fe', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_k', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_mg', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_mn', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_na', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_ti', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'addl_dil_factor', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '1',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('ams_current', 'current', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('analysis', 'wt_diss_bottle_tare', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('analysis', 'wt_diss_bottle_sample', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('analysis', 'wt_be_carrier', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('analysis', 'wt_al_carrier', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('analysis', 'wt_diss_bottle_total', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('batch', 'wt_be_carrier_init', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('batch', 'wt_be_carrier_final', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('batch', 'wt_al_carrier_init', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('batch', 'wt_al_carrier_final', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('be_ams', 'r_to_rstd', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('be_ams', 'interror', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('be_ams', 'exterror', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('be_ams', 'truefrac', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('be_ams_std', 'r10to9', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('be_ams_std', 'error', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('be_carrier', 'be_conc', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('be_carrier', 'del_be_conc', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('be_carrier', 'al_conc', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('be_carrier', 'del_al_conc', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('be_carrier', 'r10to9', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('be_carrier', 'r10to9_error', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('icp_run', 'al_result', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('icp_run', 'be_result', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'latitude', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'longitude', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'altitude', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'shield_factor', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'depth_top', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'depth_bottom', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'density', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'erosion_rate', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('sil_cl36_analysis', 'wt_spike', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('sil_cl36_analysis', 'wt_bkr_tare', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('sil_cl36_analysis', 'wt_bkr_sample', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('split', 'wt_split_bkr_tare', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('split', 'wt_split_bkr_split', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
        $this->changeColumn('split', 'wt_split_bkr_icp', 'double', '53', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             'scale' => '30',
             ));
    }

    public function down()
    {

    }
}