<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('al_ams', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('al_ams', 'analysis_id', 'integer', '2', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('al_ams', 'al_ams_std_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('al_ams', 'ams_lab_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('al_ams', 'date', 'date', '25', array(
             ));
        $this->changeColumn('al_ams', 'lab_num', 'string', '255', array(
             ));
        $this->changeColumn('al_ams', 'r_to_rstd', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('al_ams', 'interror', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('al_ams', 'exterror', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('al_ams', 'truefrac', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('al_ams', 'notes', 'string', '700', array(
             ));
        $this->changeColumn('al_ams_std', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('al_ams_std', 'name', 'string', '255', array(
             ));
        $this->changeColumn('al_ams_std', 'al_std_series_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('al_ams_std', 'r26to27', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('al_ams_std', 'error', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('al_ams_std', 'notes', 'string', '', array(
             ));
        $this->changeColumn('al_carrier', 'id', 'integer', '1', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('al_carrier', 'name', 'string', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('al_carrier', 'al_conc', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('al_carrier', 'del_al_conc', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('al_carrier', 'r26to27', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('al_carrier', 'r26to27_error', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('al_carrier', 'in_service_date', 'date', '25', array(
             ));
        $this->changeColumn('al_carrier', 'mfg_lot_no', 'string', '', array(
             ));
        $this->changeColumn('al_carrier', 'owner', 'string', '', array(
             ));
        $this->changeColumn('al_carrier', 'notes', 'string', '', array(
             ));
        $this->changeColumn('al_carrier', 'in_use', 'string', '', array(
             ));
        $this->changeColumn('al_std_series', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('al_std_series', 'code', 'string', '60', array(
             ));
        $this->changeColumn('al_std_series', 'notes', 'string', '', array(
             ));
        $this->changeColumn('alcheck_analysis', 'id', 'integer', '3', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('alcheck_analysis', 'sample_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('alcheck_analysis', 'alcheck_batch_id', 'integer', '2', array(
             'unsigned' => '1',
             'default' => '0',
             'notnull' => '1',
             ));
        $this->changeColumn('alcheck_analysis', 'number_within_batch', 'integer', '1', array(
             'unsigned' => '1',
             'default' => '0',
             'notnull' => '1',
             ));
        $this->changeColumn('alcheck_analysis', 'sample_name', 'string', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('alcheck_analysis', 'bkr_number', 'string', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('alcheck_analysis', 'wt_bkr_tare', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'flag_bkr_tare_avg', 'integer', '1', array(
             'unsigned' => '1',
             'default' => '0',
             'notnull' => '1',
             ));
        $this->changeColumn('alcheck_analysis', 'wt_bkr_sample', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'wt_bkr_soln', 'double', '53', array(
             'default' => '0',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_al', 'double', '53', array(
             'default' => '0',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_ba', 'double', '53', array(
             'default' => '0',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_be', 'double', '53', array(
             'default' => '0',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_ca', 'double', '53', array(
             'default' => '0',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_fe', 'double', '53', array(
             'default' => '0',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_k', 'double', '53', array(
             'default' => '0',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_mg', 'double', '53', array(
             'default' => '0',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_mn', 'double', '53', array(
             'default' => '0',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_na', 'double', '53', array(
             'default' => '0',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'icp_ti', 'double', '53', array(
             'default' => '0',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'addl_dil_factor', 'double', '53', array(
             'default' => '1',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('alcheck_analysis', 'notes', 'string', '', array(
             ));
        $this->changeColumn('alcheck_batch', 'id', 'integer', '2', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('alcheck_batch', 'owner', 'string', '', array(
             ));
        $this->changeColumn('alcheck_batch', 'prep_date', 'date', '25', array(
             ));
        $this->changeColumn('alcheck_batch', 'icp_date', 'date', '25', array(
             ));
        $this->changeColumn('alcheck_batch', 'description', 'string', '', array(
             ));
        $this->changeColumn('alcheck_batch', 'notes', 'string', '', array(
             ));
        $this->changeColumn('ams_current', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('ams_current', 'current', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('ams_current', 'be_ams_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('ams_current', 'al_ams_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('ams_lab', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('ams_lab', 'name', 'string', '255', array(
             'default' => '',
             'notnull' => '1',
             ));
        $this->changeColumn('ams_lab', 'full_name', 'string', '700', array(
             ));
        $this->changeColumn('analysis', 'id', 'integer', '2', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('analysis', 'batch_id', 'integer', '2', array(
             'unsigned' => '1',
             'default' => '0',
             'notnull' => '1',
             ));
        $this->changeColumn('analysis', 'sample_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('analysis', 'number_within_batch', 'integer', '1', array(
             'default' => '0',
             'notnull' => '1',
             ));
        $this->changeColumn('analysis', 'sample_name', 'string', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('analysis', 'sample_type', 'string', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('analysis', 'diss_bottle_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('analysis', 'diss_bottle_number', 'string', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('analysis', 'wt_diss_bottle_tare', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('analysis', 'wt_diss_bottle_sample', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('analysis', 'wt_be_carrier', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('analysis', 'wt_al_carrier', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('analysis', 'wt_diss_bottle_total', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('analysis', 'notes', 'string', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('batch', 'id', 'integer', '2', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('batch', 'al_carrier_id', 'integer', '1', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('batch', 'be_carrier_id', 'integer', '1', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('batch', 'owner', 'string', '', array(
             ));
        $this->changeColumn('batch', 'description', 'string', '', array(
             ));
        $this->changeColumn('batch', 'start_date', 'date', '25', array(
             'default' => '0000-00-00',
             'notnull' => '1',
             ));
        $this->changeColumn('batch', 'split_date', 'date', '25', array(
             'default' => '0000-00-00',
             'notnull' => '1',
             ));
        $this->changeColumn('batch', 'icp_date', 'date', '25', array(
             'default' => '0000-00-00',
             'notnull' => '1',
             ));
        $this->changeColumn('batch', 'be_carrier_name', 'string', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('batch', 'wt_be_carrier_init', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('batch', 'wt_be_carrier_final', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('batch', 'al_carrier_name', 'string', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('batch', 'wt_al_carrier_init', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('batch', 'wt_al_carrier_final', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('batch', 'notes', 'string', '', array(
             ));
        $this->changeColumn('batch', 'completed', 'enum', '1', array(
             'values' => 
             array(
              0 => 'y',
              1 => 'n',
             ),
             'default' => 'n',
             'notnull' => '1',
             ));
        $this->changeColumn('batch', 'spreadsheet_name', 'string', '', array(
             ));
        $this->changeColumn('batch', 'csv_name', 'string', '', array(
             ));
        $this->changeColumn('be_ams', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('be_ams', 'analysis_id', 'integer', '2', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('be_ams', 'be_ams_std_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('be_ams', 'ams_lab_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('be_ams', 'date', 'date', '25', array(
             ));
        $this->changeColumn('be_ams', 'lab_num', 'string', '255', array(
             ));
        $this->changeColumn('be_ams', 'r_to_rstd', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('be_ams', 'interror', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('be_ams', 'exterror', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('be_ams', 'truefrac', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('be_ams', 'notes', 'string', '700', array(
             ));
        $this->changeColumn('be_ams_std', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('be_ams_std', 'name', 'string', '255', array(
             ));
        $this->changeColumn('be_ams_std', 'be_std_series_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('be_ams_std', 'r10to9', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('be_ams_std', 'error', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('be_ams_std', 'notes', 'string', '', array(
             ));
        $this->changeColumn('be_carrier', 'id', 'integer', '1', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('be_carrier', 'name', 'string', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('be_carrier', 'be_conc', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('be_carrier', 'del_be_conc', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('be_carrier', 'al_conc', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('be_carrier', 'del_al_conc', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('be_carrier', 'r10to9', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('be_carrier', 'r10to9_error', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('be_carrier', 'in_service_date', 'date', '25', array(
             ));
        $this->changeColumn('be_carrier', 'mfg_lot_no', 'string', '', array(
             ));
        $this->changeColumn('be_carrier', 'owner', 'string', '', array(
             ));
        $this->changeColumn('be_carrier', 'notes', 'string', '', array(
             ));
        $this->changeColumn('be_carrier', 'in_use', 'string', '', array(
             ));
        $this->changeColumn('be_std_series', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('be_std_series', 'code', 'string', '60', array(
             ));
        $this->changeColumn('be_std_series', 'notes', 'string', '', array(
             ));
        $this->changeColumn('diss_bottle', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('diss_bottle', 'bottle_number', 'string', '', array(
             ));
        $this->changeColumn('icp_run', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('icp_run', 'split_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('icp_run', 'run_num', 'integer', '1', array(
             'unsigned' => '1',
             'default' => '1',
             'notnull' => '1',
             ));
        $this->changeColumn('icp_run', 'al_result', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('icp_run', 'be_result', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('icp_run', 'use_al', 'enum', '1', array(
             'values' => 
             array(
              0 => 'y',
              1 => 'n',
             ),
             'default' => 'y',
             'notnull' => '1',
             ));
        $this->changeColumn('icp_run', 'use_be', 'enum', '1', array(
             'values' => 
             array(
              0 => 'y',
              1 => 'n',
             ),
             'default' => 'y',
             'notnull' => '1',
             ));
        $this->changeColumn('project', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('project', 'name', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('project', 'date_added', 'timestamp', '25', array(
             ));
        $this->changeColumn('project', 'description', 'string', '', array(
             ));
        $this->changeColumn('project_sample', 'project_id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             ));
        $this->changeColumn('project_sample', 'sample_id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             ));
        $this->changeColumn('sample', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('sample', 'name', 'string', '255', array(
             'default' => '',
             'notnull' => '1',
             ));
        $this->changeColumn('sample', 'latitude', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'longitude', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'altitude', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'antarctic', 'integer', '1', array(
             'default' => '0',
             'notnull' => '1',
             ));
        $this->changeColumn('sample', 'shield_factor', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'depth_top', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'depth_bottom', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'density', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'erosion_rate', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('sample', 'notes', 'string', '', array(
             ));
        $this->changeColumn('sil_cl36_analysis', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('sil_cl36_analysis', 'sample_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('sil_cl36_analysis', 'sample_name', 'string', '255', array(
             'default' => '',
             'notnull' => '1',
             ));
        $this->changeColumn('sil_cl36_analysis', 'cl36_batch_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('sil_cl36_analysis', 'calib_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('sil_cl36_analysis', 'cl37_spike_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('sil_cl36_analysis', 'sample_type', 'enum', '6', array(
             'values' => 
             array(
              0 => 'SAMPLE',
              1 => 'CALIB',
              2 => 'BLANK',
             ),
             'default' => 'SAMPLE',
             'notnull' => '1',
             ));
        $this->changeColumn('sil_cl36_analysis', 'wt_spike', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('sil_cl36_analysis', 'wt_bkr_tare', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('sil_cl36_analysis', 'wt_bkr_sample', 'double', '53', array(
             'scale' => '30',
             ));
        $this->changeColumn('sil_cl36_batch', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('sil_cl36_batch', 'owner', 'string', '60', array(
             ));
        $this->changeColumn('sil_cl36_batch', 'cl_carrier_id', 'integer', '4', array(
             ));
        $this->changeColumn('split', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('split', 'analysis_id', 'integer', '2', array(
             'unsigned' => '1',
             'notnull' => '1',
             ));
        $this->changeColumn('split', 'split_bkr_id', 'integer', '4', array(
             'unsigned' => '1',
             'notnull' => '1',
             ));
        $this->changeColumn('split', 'split_num', 'integer', '1', array(
             'unsigned' => '1',
             'default' => '1',
             'notnull' => '1',
             ));
        $this->changeColumn('split', 'split_bkr_name', 'string', '', array(
             ));
        $this->changeColumn('split', 'wt_split_bkr_tare', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('split', 'wt_split_bkr_split', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('split', 'wt_split_bkr_icp', 'double', '53', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '30',
             ));
        $this->changeColumn('split_bkr', 'id', 'integer', '4', array(
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('split_bkr', 'bkr_number', 'string', '', array(
             ));
    }

    public function down()
    {

    }
}