<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version28 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('al_carrier', 'owner', 'string', '', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('al_carrier', 'id', 'integer', '1', array(
             'fixed' => '0',
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('al_carrier', 'name', 'string', '', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '1',
             'autoincrement' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('al_carrier', 'owner');
    }
}