<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version32 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('split', 'split_bkr_id', 'integer', '8', array(
             'unsigned' => '1',
             ));
    }

    public function down()
    {

    }
}