<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlCarrierTable extends Doctrine_Table
{
	public function getList()
	{
		$q = Doctrine_Query::create()
			->from('AlCarrier alc')
			->select('alc.id, alc.name')
			->execute();
		return $q;
	}
}