<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Analysis extends BaseAnalysis
{
	public function setUp()
	{
		parent::setUp();
		
		$this->hasOne('Batch', array(
				'local' => 'batch_id',
				'foreign' => 'id'
			)
		);

		$this->hasMany('Split as Splits', array(
				'local' => 'id',
				'foreign' => 'analysis_id'
			)
		);
	}
}