<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BeCarrierTable extends Doctrine_Table
{
    public function getSelectOptions($batch)
    {
        $carriers = $this->createQuery('c')->select('c.id, c.name')->execute();
        
        $options = '';
        foreach ($carriers as $c) {
            $options .= "<option value=$c->id";
            if (isset($batch->BeCarrier) && $c->id == $batch->BeCarrier->id) {
                $options .= ' selected';
            }
           $options .= "> $c->name";
        }
        
        return $options;
    }
}