<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BeCarrierTable extends Doctrine_Table
{
    public function getSelectOptions($carrier_id)
    {
        $carriers = $this->createQuery('c')
            ->select('c.id, c.name')
            ->orderBy('c.in_service_date DESC')
            ->execute();
        
        $options = '';
        foreach ($carriers as $c) {
            $options .= "<option value=$c->id";
            if ($c->id == $carrier_id) {
                $options .= ' selected';
            }
           $options .= "> $c->name";
        }
        
        return $options;
    }
}