<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcpRun extends BaseIcpRun
{
	public function setUp()
	{
		parent::setUp();

		$this->hasOne('Split', array(
				'local' => 'split_id',
				'foreign' => 'id'
			)
		);
	}
}