<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IcpRunTable extends Doctrine_Table
{

    public function removeExcessRuns(&$split, $nRemainingRuns)
    {
        return Doctrine_Query::create()
            ->delete('IcpRun')
            ->where('split_id = ?', $split->id)
            ->addWhere('run_num > ?', $nRemainingRuns)
            ->execute();
    }

}