<?php

/**
 * Project
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Project extends BaseProject
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Sample', array(
                'refClass' => 'ProjectSample',
                'local' => 'project_id',
                'foreign' => 'sample_id',
            )
        );
    }
}