<?php

/**
 * Sample
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Sample extends BaseSample
{
    public function setUp()
    {
        $this->hasMany('Project', array(
                'refClass' => 'ProjectSample',
                'local' => 'project_id',
                'foreign' => 'sample_id'
            )
        );
    }
}