<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SplitBkrTable extends Doctrine_Table
{
    /**
	 *
	 * @return Doctrine_Collection
	 */
	public function getList()
	{
		return Doctrine_Query::create()
			->from('SplitBkr b')
			->select('b.id, b.bkr_number')
			->orderBy('b.id asc')
			->execute();
	}

}